name          'chriscowley-owncloud'
version       '0.1.0'
source        'https://github.com/chriscowley/puppet-owncloud.git'
author        'Chris Cowley'
license       'Apache License, Version 2.0'
summary       'Module for installing and (optionally) configuring Owncloud'
description   'Install Owncloud'
project_page  'https://github.com/chriscowley/puppet-owncloud'

dependency 'puppetlabs/stdlib'
